# -*- coding: utf-8 -*-
"""UCL_2026_Predictor_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5bpwH1VpBkE6e77lFzLQ0yAaooVWNvI

# 🏆 UCL 2025/26 — AI Champion Predictor v2
### Road to Budapest | Data 7 Pertandingan Terakhir Liga

**Sumber:** UEFA.com, Premier League, La Liga, Bundesliga, Ligue 1, Serie A, Liga Portugal, Super Lig *(per 27 Feb 2026)*

**Fitur v2:** Form rating dinamis 7 laga terakhir · Heatmap form · Enhanced model · 15K Monte Carlo · Mode Jagoan
---
"""

!pip install pandas numpy matplotlib seaborn scikit-learn plotly -q
import pandas as pd, numpy as np, matplotlib.pyplot as plt
import matplotlib.patches as mpatches, matplotlib.gridspec as gridspec
import seaborn as sns, random, warnings
from sklearn.preprocessing import MinMaxScaler
warnings.filterwarnings('ignore')
plt.style.use('dark_background')
print('✅ Library siap!')

"""## 📊 Load Data CSV
Upload file **ucl_2026_detailed.csv** atau gunakan data embed di bawah.
"""

import io

# OPSI A: Upload file CSV
# from google.colab import files; uploaded = files.upload(); df = pd.read_csv(list(uploaded.keys())[0])

# OPSI B: Data embed (langsung jalan tanpa upload)
csv_data = '''team,country,league,league_position,league_pts,league_gp,league_wins,league_draws,league_losses,league_gf,league_ga,league_gd,ucl_phase_rank,ucl_wins,ucl_draws,ucl_losses,ucl_gf,ucl_ga,ucl_pts,ucl_titles,uefa_coeff_rank,reached_via,key_player,coach,last7_m1,last7_r1,last7_gf1,last7_ga1,last7_m2,last7_r2,last7_gf2,last7_ga2,last7_m3,last7_r3,last7_gf3,last7_ga3,last7_m4,last7_r4,last7_gf4,last7_ga4,last7_m5,last7_r5,last7_gf5,last7_ga5,last7_m6,last7_r6,last7_gf6,last7_ga6,last7_m7,last7_r7,last7_gf7,last7_ga7,last7_wins,last7_draws,last7_losses,last7_gf_total,last7_ga_total,last7_pts,domestic_form_rating,squad_depth_score,experience_score,coach_quality_score,injury_concern,avg_goals_scored_last7,avg_goals_conceded_last7
Arsenal,England,Premier League,1,62,28,19,5,4,66,29,37,1,8,0,0,23,4,24,0,8,Direct,Bukayo Saka,Mikel Arteta,vs Tottenham (H),W,4,1,vs Sunderland (A),W,3,1,vs Brentford (A),W,2,0,vs Wolves (H),W,2,0,vs Nottm Forest (H),W,3,0,vs Leeds (A),D,1,1,vs Man City (H),W,2,1,5,1,1,17,4,16,9.2,9,7,9,Low,2.43,0.57
Bayern Munich,Germany,Bundesliga,1,55,24,17,4,3,67,28,39,2,7,0,1,22,8,21,6,2,Direct,Harry Kane,Vincent Kompany,vs Frankfurt (H),W,3,2,vs Mainz (A),W,4,1,vs Dortmund (H),W,3,0,vs Hoffenheim (A),W,5,1,vs Union Berlin (H),W,4,0,vs Augsburg (A),W,2,1,vs Wolfsburg (H),D,1,1,6,1,0,22,6,19,9.5,9,10,8,Low,3.14,0.86
Liverpool,England,Premier League,3,52,27,15,7,5,62,38,24,3,6,1,1,18,9,19,6,3,Direct,Mohamed Salah,Arne Slot,vs Crystal Palace (H),W,1,0,vs Fulham (A),D,1,1,vs Aston Villa (H),W,3,1,vs Everton (A),W,2,0,vs Leicester (H),W,4,1,vs Wolves (A),D,2,2,vs Leeds (H),W,3,1,5,2,0,16,6,17,8.5,9,9,8,Low,2.29,0.86
Real Madrid,Spain,La Liga,2,52,25,16,4,5,61,32,29,4,5,2,1,19,9,17,15,1,Playoff (vs Benfica),Kylian Mbappe,Alvaro Arbeloa,vs Getafe (H),W,3,0,vs Villarreal (A),W,2,1,vs Real Betis (H),W,2,0,vs Osasuna (A),D,1,1,vs Girona (H),W,4,1,vs Celta Vigo (A),L,1,2,vs Espanyol (H),W,2,0,5,1,1,15,5,16,8.0,10,10,7,Medium,2.14,0.71
PSG,France,Ligue 1,1,57,26,18,3,5,67,31,36,5,5,1,2,20,11,16,1,4,Playoff (vs Sporting CP),Ousmane Dembele,Luis Enrique,vs Le Havre (H),W,4,0,vs Monaco (H),W,3,1,vs Marseille (A),W,2,1,vs Lens (H),D,2,2,vs Nantes (A),W,3,0,vs Lyon (H),W,4,1,vs Rennes (A),W,2,0,6,1,0,20,5,19,8.8,9,8,9,Low,2.86,0.71
Barcelona,Spain,La Liga,1,56,25,17,5,3,69,28,41,5,5,1,2,22,14,16,5,7,Direct,Lamine Yamal,Hansi Flick,vs Villarreal (H),W,4,1,vs Real Sociedad (A),W,2,0,vs Espanyol (H),W,3,1,vs Betis (A),D,1,1,vs Mallorca (H),W,2,0,vs Girona (A),W,3,2,vs Alaves (H),W,5,0,6,1,0,20,5,19,9.0,8,9,8,Medium,2.86,0.71
Man City,England,Premier League,4,49,28,14,7,7,56,43,13,7,5,0,3,17,12,15,1,5,Direct,Erling Haaland,Pep Guardiola,vs Leeds (A),W,3,1,vs Newcastle (H),D,1,1,vs Aston Villa (A),L,1,2,vs Ipswich (H),W,4,0,vs Southampton (A),W,2,0,vs Brentford (A),L,0,1,vs West Ham (H),W,3,1,4,1,2,14,6,13,7.5,10,9,10,Medium,2.00,0.86
Newcastle,England,Premier League,8,43,28,12,7,9,49,44,5,8,4,2,2,13,10,14,0,17,Direct,Alexander Isak,Eddie Howe,vs Man City (A),D,1,1,vs Bournemouth (H),W,3,1,vs Everton (A),W,2,1,vs Burnley (H),W,4,0,vs Wolves (A),D,1,1,vs Crystal Palace (H),L,1,2,vs Sunderland (A),W,2,0,4,2,1,14,6,14,7.2,7,5,7,Low,2.00,0.86
Atalanta,Italy,Serie A,7,38,26,11,5,10,47,44,3,15,4,1,3,10,10,13,0,15,Playoff (vs Dortmund),Charles De Ketelaere,Raffaele Palladino,vs Roma (H),W,3,1,vs Genoa (A),D,1,1,vs Inter (H),L,0,3,vs Lazio (A),W,2,1,vs Torino (H),W,3,0,vs Napoli (A),D,1,1,vs Monza (H),W,4,0,4,2,1,14,7,14,7.0,7,5,8,Medium,2.00,1.00
Atletico Madrid,Spain,La Liga,4,45,25,13,6,6,55,37,18,14,4,1,3,17,15,13,0,12,Playoff (vs Club Brugge),Julian Alvarez,Diego Simeone,vs Real Oviedo (H),W,4,0,vs Osasuna (A),W,2,0,vs Real Sociedad (H),W,3,1,vs Alaves (A),D,1,1,vs Leganes (H),W,4,1,vs Girona (A),L,0,2,vs Espanyol (H),W,3,0,5,1,1,17,5,16,7.8,8,8,9,Low,2.43,0.71
Galatasaray,Turkey,Super Lig,1,60,26,19,3,4,62,24,38,20,3,1,4,9,11,10,0,47,Playoff (vs Juventus),Victor Osimhen,Okan Buruk,vs Besiktas (H),W,3,1,vs Trabzonspor (A),W,2,0,vs Konyaspor (H),W,4,0,vs Antalyaspor (A),D,1,1,vs Sivasspor (H),W,3,0,vs Fenerbahce (A),D,1,1,vs Kasimpasa (H),W,4,1,5,2,0,18,4,17,8.5,6,5,7,Low,2.57,0.57
Bayer Leverkusen,Germany,Bundesliga,4,43,24,13,4,7,55,37,18,9,4,2,2,13,8,14,0,9,Playoff (vs Olympiacos),Florian Wirtz,Xabi Alonso,vs Koln (H),W,4,1,vs Heidenheim (A),W,2,0,vs Wolfsburg (H),W,3,1,vs Bochum (A),L,1,2,vs Schalke (H),W,3,0,vs Werder (A),D,1,1,vs Dortmund (H),W,2,1,5,1,1,16,6,16,8.0,8,6,9,Low,2.29,0.86
Chelsea,England,Premier League,5,47,28,14,5,9,55,47,8,6,5,1,2,17,10,16,2,11,Direct,Cole Palmer,Liam Rosenior,vs Tottenham (H),W,3,1,vs Brentford (A),D,1,1,vs Wolves (H),W,2,0,vs Man City (A),D,1,1,vs Leicester (H),W,3,0,vs Southampton (A),W,4,1,vs Arsenal (A),L,0,2,4,2,1,14,6,14,7.5,8,7,7,Medium,2.00,0.86
Tottenham,England,Premier League,16,27,28,7,6,15,43,62,-19,11,4,0,4,14,14,12,0,20,Direct,Son Heung-min,Igor Tudor,vs Liverpool (A),L,4,1,vs Fulham (H),L,1,4,vs Wolves (A),W,3,0,vs Brighton (H),D,1,1,vs Leicester (A),L,0,2,vs Everton (H),W,2,1,vs Brentford (A),L,0,3,2,1,4,11,11,7,5.0,7,6,6,High,1.57,1.57
Sporting CP,Portugal,Liga Portugal,1,61,23,19,4,0,55,16,39,7,4,2,2,14,10,14,0,21,Direct,Viktor Gyokeres,Rui Borges,vs Braga (H),W,3,0,vs Porto (A),W,2,1,vs Benfica (H),W,3,1,vs Estoril (A),W,4,0,vs Rio Ave (H),W,3,0,vs Guimaraes (A),D,1,1,vs Famalicao (H),W,3,0,6,1,0,19,3,19,9.3,7,5,7,Low,2.71,0.43
Bodo/Glimt,Norway,Eliteserien,N/A,N/A,0,0,0,0,0,0,0,23,2,3,3,14,15,9,0,34,Playoff (vs Inter),Jens Petter Hauge,Kjetil Knutsen,vs UCL Inter (A),W,3,1,vs UCL Inter (H),W,2,1,vs UCL Man City (H),W,3,1,vs UCL Atletico (A),W,2,1,vs UCL Galatasaray (H),L,1,3,vs UCL Dortmund (A),D,1,1,vs UCL Slavia (H),D,2,2,4,2,1,14,10,14,7.5,5,3,8,Low,2.00,1.43'''

df = pd.read_csv(io.StringIO(csv_data))
df['league_pts'] = pd.to_numeric(df['league_pts'], errors='coerce')
df['league_position'] = pd.to_numeric(df['league_position'], errors='coerce')
print(f'✅ {len(df)} tim dimuat, {len(df.columns)} kolom')
df[['team','league','league_position','last7_wins','last7_draws','last7_losses','last7_gf_total','last7_ga_total','last7_pts']].head(16)

"""## 🔥 Analisis Form 7 Pertandingan Terakhir"""

form_data = []
for _, row in df.iterrows():
    results = [row[f'last7_r{i}'] for i in range(1, 8)]
    weights = [0.25, 0.20, 0.18, 0.13, 0.10, 0.08, 0.06]
    score_map = {'W': 3, 'D': 1, 'L': 0}
    wf = sum(score_map.get(r,0) * w for r,w in zip(results,weights))
    rating = (wf / sum(3*w for w in weights)) * 10
    form_data.append({'team': row['team'], 'league': row['league'],
                      'form_string': ''.join(results), 'weighted_form_rating': round(rating,2),
                      'last7_pts': row['last7_pts'], 'injury': row['injury_concern'],
                      'avg_gf': row['avg_goals_scored_last7'], 'avg_ga': row['avg_goals_conceded_last7']})

form_df = pd.DataFrame(form_data).sort_values('weighted_form_rating', ascending=False).reset_index(drop=True)
icons = {'W':'🟢','D':'🟡','L':'🔴'}
inj = {'Low':'🟢','Medium':'🟡','High':'🔴'}

print(f'{"#":<3} {"Tim":<20} {"Liga":<16} {"Form (terbaru→lama)":<28} {"Pts":<5} {"Rating":<7} Cedera')
print('-'*95)
for i, r in form_df.iterrows():
    fi = ' '.join(icons.get(c,'⚫') for c in r['form_string'])
    print(f"{i+1:<3} {r['team']:<20} {r['league']:<16} {fi:<40} {r['last7_pts']:<5} {r['weighted_form_rating']:<7.1f} {inj.get(r['injury'],'⚫')} {r['injury']}")

print(f'\n🔥 HOT: {form_df.iloc[0]["team"]} ({form_df.iloc[0]["form_string"]}) — {form_df.iloc[0]["weighted_form_rating"]:.1f}/10')
print(f'❄️  COLD: {form_df.iloc[-1]["team"]} ({form_df.iloc[-1]["form_string"]}) — {form_df.iloc[-1]["weighted_form_rating"]:.1f}/10')

# HEATMAP FORM
fig, axes = plt.subplots(1, 2, figsize=(18, 9))
fig.patch.set_facecolor('#0A0E1A')
clrs = {'W':'#00C853','D':'#FFD600','L':'#FF1744'}
teams_ord = form_df['team'].tolist()

ax1 = axes[0]; ax1.set_facecolor('#0A0E1A')
for ti, team in enumerate(teams_ord):
    row_d = df[df['team']==team].iloc[0]
    for mi in range(7):
        res = row_d[f'last7_r{mi+1}']
        rect = plt.Rectangle((mi, len(teams_ord)-ti-1), 0.9, 0.85, color=clrs.get(res,'#444'), alpha=0.85)
        ax1.add_patch(rect)
        ax1.text(mi+0.45, len(teams_ord)-ti-1+0.425, res, ha='center', va='center', fontsize=8, fontweight='bold', color='white')

ax1.set_xlim(0,7); ax1.set_ylim(0,len(teams_ord))
ax1.set_xticks(np.arange(7)+0.45)
ax1.set_xticklabels(['M1\n(terbaru)','M2','M3','M4','M5','M6','M7\n(terlama)'], color='white', fontsize=8)
ax1.set_yticks(np.arange(len(teams_ord))+0.425)
ax1.set_yticklabels(reversed(teams_ord), color='white', fontsize=8.5)
ax1.set_title('📅 Heatmap Form 7 Pertandingan Terakhir', color='gold', fontsize=11, fontweight='bold')
for sp in ax1.spines.values(): sp.set_visible(False)
ax1.legend(handles=[mpatches.Patch(color=c,label=l) for c,l in zip(['#00C853','#FFD600','#FF1744'],['Menang','Seri','Kalah'])],
           loc='lower right', facecolor='#1A1A2E', labelcolor='white', fontsize=8)

ax2 = axes[1]; ax2.set_facecolor('#0A0E1A')
cmap = plt.cm.RdYlGn(np.linspace(0.2,0.9,len(form_df)))
bars = ax2.barh(range(len(form_df)), form_df['weighted_form_rating'], color=cmap, edgecolor='white', linewidth=0.2, height=0.7)
ax2.set_yticks(range(len(form_df)))
ax2.set_yticklabels(form_df['team'], color='white', fontsize=8.5)
ax2.set_title('📊 Weighted Form Rating (0-10)', color='gold', fontsize=11, fontweight='bold')
ax2.tick_params(colors='white')
for sp in ax2.spines.values(): sp.set_color('#222')
for bar, val in zip(bars, form_df['weighted_form_rating']):
    ax2.text(bar.get_width()+0.05, bar.get_y()+bar.get_height()/2, f'{val:.1f}', va='center', color='white', fontsize=8, fontweight='bold')

plt.tight_layout()
plt.savefig('ucl_form_heatmap.png', dpi=150, bbox_inches='tight', facecolor='#0A0E1A')
plt.show(); print('✅ Heatmap tersimpan!')

"""## 📋 Detail 7 Pertandingan — Pilih Tim"""

TEAM_DETAIL = 'Arsenal'  # <-- GANTI

row = df[df['team']==TEAM_DETAIL]
if row.empty: print('❌ Tim tidak ditemukan!')
else:
    row = row.iloc[0]
    fd = form_df[form_df['team']==TEAM_DETAIL].iloc[0]
    ri = {'W':'✅ MENANG','D':'🟡 SERI  ','L':'❌ KALAH '}
    print(f'=== ❤️  {TEAM_DETAIL.upper()} — Form Detail 7 Laga ({row["league"]}) ===')
    print(f'Pelatih: {row["coach"]} | Key Player: {row["key_player"]} | Cedera: {row["injury_concern"]}\n')
    total_gf = total_ga = pts = 0
    for i in range(1,8):
        m,r,gf,ga = row[f'last7_m{i}'],row[f'last7_r{i}'],int(row[f'last7_gf{i}']),int(row[f'last7_ga{i}'])
        total_gf+=gf; total_ga+=ga; pts+={'W':3,'D':1,'L':0}.get(r,0)
        print(f'  {i}. {m:<38} {ri.get(r,"?")}  {gf}-{ga}')
    print(f'\n  TOTAL: W{row["last7_wins"]} D{row["last7_draws"]} L{row["last7_losses"]} | GF:{total_gf} GA:{total_ga} | {pts} poin')
    print(f'  Weighted Form Rating: {fd["weighted_form_rating"]:.1f}/10')
    print(f'  UCL League Phase   : W{row["ucl_wins"]} D{row["ucl_draws"]} L{row["ucl_losses"]} ({row["ucl_pts"]} pts)')

"""## 🤖 Model Prediksi v2 (Enhanced dengan Form Terkini)"""

df = df.merge(form_df[['team','weighted_form_rating']], on='team', how='left')
df['ucl_gd'] = df['ucl_gf'] - df['ucl_ga']

WEIGHTS = {
    'weighted_form_rating': 0.30,  # Form 7 laga terakhir
    'squad_depth_score':    0.17,
    'experience_score':     0.18,
    'coach_quality_score':  0.13,
    'ucl_gd_norm':          0.10,
    'ucl_titles_norm':      0.08,
    'avg_attack_norm':      0.04,
}

scaler = MinMaxScaler()
df_m = df.copy()
for orig, new in [('ucl_gd','ucl_gd_norm'),('ucl_titles','ucl_titles_norm'),
                   ('avg_goals_scored_last7','avg_attack_norm'),
                   ('weighted_form_rating','weighted_form_rating'),
                   ('squad_depth_score','squad_depth_score'),
                   ('experience_score','experience_score'),
                   ('coach_quality_score','coach_quality_score')]:
    df_m[new] = scaler.fit_transform(df_m[orig].values.reshape(-1,1)).flatten()

inj_pen = {'Low':0.0,'Medium':-0.05,'High':-0.12}
df_m['composite'] = sum(df_m[f]*w for f,w in WEIGHTS.items()) + df_m['injury_concern'].map(inj_pen).fillna(0)
df_m['composite'] = df_m['composite'].clip(lower=0)
df_m['prob'] = (df_m['composite']/df_m['composite'].sum()*100).round(2)
df_m = df_m.sort_values('prob', ascending=False).reset_index(drop=True)
df_m['rank'] = range(1,17)

medals = ['🥇','🥈','🥉']+['  ']*13
print('=== 🤖 HASIL MODEL v2 (form-weighted) ===')
for i,row in df_m.iterrows():
    bar = '█'*int(row['prob']*1.8)
    inj_i = {'Low':'🟢','Medium':'🟡','High':'🔴'}.get(row['injury_concern'],'⚫')
    print(f"{medals[i]} {row['team']:<20} Form:{row['weighted_form_rating']:.1f}  {inj_i}  {bar} {row['prob']:.1f}%")

prob_dict = dict(zip(df_m['team'], df_m['prob']))
print(f'\n🎯 PREDIKSI: {df_m.iloc[0]["team"].upper()} ({df_m.iloc[0]["prob"]:.1f}%)')

"""## 🎲 Monte Carlo Simulation (15.000 turnamen)"""

BRACKET = [
    ('PSG','Chelsea'),('Galatasaray','Liverpool'),('Real Madrid','Man City'),('Atalanta','Bayern Munich'),
    ('Newcastle','Barcelona'),('Atletico Madrid','Tottenham'),('Bodo/Glimt','Sporting CP'),('Bayer Leverkusen','Arsenal')
]

def sim_match(t1,t2,prob_dict,upset=0.18):
    p1,p2 = prob_dict.get(t1,5),prob_dict.get(t2,5)
    noise = random.gauss(0,upset*(p1+p2))
    p1a,p2a = max(0.05,p1+noise),max(0.05,p2-noise)
    return t1 if random.random()<p1a/(p1a+p2a) else t2

def sim_tournament(bracket,prob_dict):
    r16 = [sim_match(a,b,prob_dict) for a,b in bracket]
    qf  = [sim_match(r16[i],r16[i+1],prob_dict) for i in range(0,8,2)]
    sf  = [sim_match(qf[0],qf[1],prob_dict), sim_match(qf[2],qf[3],prob_dict)]
    return sim_match(sf[0],sf[1],prob_dict)

N=15000; random.seed(42); np.random.seed(42); counts={}
for _ in range(N):
    c=sim_tournament(BRACKET,prob_dict); counts[c]=counts.get(c,0)+1

mc_df = pd.DataFrame([{'team':t,'count':c,'pct':round(c/N*100,2)} for t,c in sorted(counts.items(),key=lambda x:-x[1])])
print(f'✅ {N:,} simulasi selesai!\n=== 🎲 MONTE CARLO RESULTS ===')
for i,r in mc_df.iterrows():
    bar='█'*int(r['pct']*1.2)
    print(f"{'🥇🥈🥉'[i] if i<3 else '  '} {r['team']:<20} {bar:<25} {r['pct']:>5.1f}%  ({int(r['count']):>5} kali)")
print(f'\n🏆 MC WINNER: {mc_df.iloc[0]["team"].upper()} — {mc_df.iloc[0]["pct"]:.1f}%')

"""## 📊 Visualisasi Dashboard Lengkap"""

merged = df_m.merge(mc_df[['team','pct']].rename(columns={'pct':'mc_pct'}), on='team', how='left')
merged['mc_pct'] = merged['mc_pct'].fillna(0)
PAL=['#FFD700','#FFC107','#FF9800','#FF7043','#EF5350','#E91E63','#9C27B0','#673AB7','#3F51B5','#2196F3','#03A9F4','#00BCD4','#009688','#4CAF50','#8BC34A','#CDDC39']

fig,axes=plt.subplots(2,2,figsize=(18,14)); fig.patch.set_facecolor('#060B14')
fig.suptitle('🏆 UCL 2025/26 — Dashboard Prediksi v2.0 (Data 7 Laga Terakhir)', fontsize=14, color='gold', fontweight='bold')

# 1. MC Bar
ax1=axes[0,0]; ax1.set_facecolor('#060B14')
smc=mc_df.sort_values('pct'); bars=ax1.barh(smc['team'],smc['pct'],color=PAL[:len(smc)],edgecolor='white',linewidth=0.2)
[ax1.text(b.get_width()+0.1,b.get_y()+b.get_height()/2,f'{v:.1f}%',va='center',color='white',fontsize=7) for b,v in zip(bars,smc['pct'])]
ax1.set_title('🎲 Monte Carlo (15K)',color='#00D4FF',fontweight='bold',fontsize=9); ax1.tick_params(colors='white',labelsize=7.5)
for sp in ax1.spines.values(): sp.set_color('#1A1A2E')

# 2. Form vs MC Scatter
ax2=axes[0,1]; ax2.set_facecolor('#060B14')
for i,row in merged.iterrows():
    fr=form_df[form_df['team']==row['team']]['weighted_form_rating'].values
    if len(fr):
        c='#FF1744' if row['injury_concern']=='High' else '#FFD700' if row['injury_concern']=='Low' else '#FF9800'
        ax2.scatter(fr[0],row['mc_pct'],s=row['mc_pct']*15+20,color=c,alpha=0.85,edgecolors='white',linewidth=0.5,zorder=3)
        ax2.annotate(row['team'],(fr[0],row['mc_pct']),textcoords='offset points',xytext=(4,3),fontsize=6.5,color='white',alpha=0.9)
ax2.set_xlabel('Form Rating',color='white',fontsize=8); ax2.set_ylabel('MC Win %',color='white',fontsize=8)
ax2.set_title('📈 Form Rating vs Peluang Menang',color='#00D4FF',fontweight='bold',fontsize=9)
ax2.tick_params(colors='white',labelsize=7)
for sp in ax2.spines.values(): sp.set_color('#1A1A2E')
ax2.legend(handles=[mpatches.Patch(color=c,label=l) for c,l in zip(['#FFD700','#FF9800','#FF1744'],['Cedera:Low','Cedera:Med','Cedera:High'])],
           facecolor='#1A1A2E',labelcolor='white',fontsize=7)

# 3. Gol Dibuat vs Kemasukan (7 laga)
ax3=axes[1,0]; ax3.set_facecolor('#060B14')
for i,row in df.iterrows():
    ax3.scatter(row['avg_goals_scored_last7'],row['avg_goals_conceded_last7'],s=80,color=PAL[i],edgecolors='white',linewidth=0.4,zorder=3)
    ax3.annotate(row['team'],(row['avg_goals_scored_last7'],row['avg_goals_conceded_last7']),textcoords='offset points',xytext=(4,3),fontsize=6.5,color='white')
ax3.axvline(df['avg_goals_scored_last7'].mean(),color='#444',linestyle='--',linewidth=0.8)
ax3.axhline(df['avg_goals_conceded_last7'].mean(),color='#444',linestyle='--',linewidth=0.8)
ax3.set_xlabel('Rata-rata Gol/Laga',color='white',fontsize=8); ax3.set_ylabel('Rata-rata Kemasukan/Laga',color='white',fontsize=8)
ax3.set_title('⚽ Serangan vs Pertahanan (7 Laga Terakhir)',color='#00D4FF',fontweight='bold',fontsize=9)
ax3.tick_params(colors='white',labelsize=7)
for sp in ax3.spines.values(): sp.set_color('#1A1A2E')

# 4. Model vs MC Top8
ax4=axes[1,1]; ax4.set_facecolor('#060B14')
top8=merged.sort_values('mc_pct',ascending=False).head(8); x=np.arange(8); w=0.35
ax4.bar(x-w/2,top8['prob'],w,label='Model v2',color='#00D4FF',alpha=0.85,edgecolor='white',linewidth=0.3)
ax4.bar(x+w/2,top8['mc_pct'],w,label='Monte Carlo',color='#FFD700',alpha=0.85,edgecolor='white',linewidth=0.3)
ax4.set_xticks(x); ax4.set_xticklabels(top8['team'],rotation=25,ha='right',color='white',fontsize=8)
ax4.set_title('🔄 Model v2 vs Monte Carlo (Top 8)',color='#00D4FF',fontweight='bold',fontsize=9)
ax4.legend(facecolor='#1A1A2E',labelcolor='white',fontsize=8); ax4.tick_params(colors='white',labelsize=7)
for sp in ax4.spines.values(): sp.set_color('#1A1A2E')

plt.tight_layout()
plt.savefig('ucl_dashboard_v2.png',dpi=150,bbox_inches='tight',facecolor='#060B14')
plt.show(); print('✅ Dashboard v2 tersimpan!')

"""## 🏟️ Simulasi Bracket Lengkap"""

def bw(t1,t2):
    p1,p2=prob_dict.get(t1,5),prob_dict.get(t2,5)
    w=t1 if p1>=p2 else t2; l=t2 if p1>=p2 else t1
    return w,l,max(p1,p2)/(p1+p2)*100

def pm(t1,t2,label=''):
    w,l,c=bw(t1,t2)
    print(f'   {t1:<22} vs {t2:<22} → ✅ {w} ({c:.0f}%)')
    return w

print('🏟️ BRACKET UCL 2025/26 v2\n')
print('='*65+'\n🔵 ROUND OF 16'); r16=[pm(a,b) for a,b in BRACKET]
print(f'\n→ QF: {", ".join(r16)}')
print('\n'+'='*65+'\n🟡 QUARTER-FINAL'); qf=[pm(r16[i],r16[i+1]) for i in range(0,8,2)]
print('\n'+'='*65+'\n🟠 SEMI-FINAL'); sf=[pm(qf[0],qf[1]),pm(qf[2],qf[3])]
print('\n'+'='*65+'\n🔴 FINAL BUDAPEST 🇭🇺 — 30 MEI 2026')
champ,ru,conf=bw(sf[0],sf[1])
print(f'\n   🆚 {sf[0]} vs {sf[1]}')
print(f'\n   🏆 JUARA: {champ.upper()}')
print(f'   🥈 Runner-up: {ru}')
print(f'   📊 Keyakinan: {conf:.1f}%')
fd2=form_df[form_df['team']==champ]
if not fd2.empty: print(f'   🔥 Form {champ}: {fd2.iloc[0]["form_string"]} ({fd2.iloc[0]["weighted_form_rating"]:.1f}/10)')

"""## ❤️ Mode Jagoan v2"""

MY_TEAM = 'Arsenal'  # <-- GANTI

row=df[df['team']==MY_TEAM]
if row.empty: print('❌ Tim tidak ditemukan!')
else:
    row=row.iloc[0]; md=df_m[df_m['team']==MY_TEAM].iloc[0]
    fd=form_df[form_df['team']==MY_TEAM].iloc[0]
    mc_row=mc_df[mc_df['team']==MY_TEAM]
    mc_pct=mc_row.iloc[0]['pct'] if not mc_row.empty else 0
    ri={'W':'🟢 W','D':'🟡 D','L':'🔴 L'}
    print(f'=== ❤️  JAGOAN v2: {MY_TEAM.upper()} ===')
    print(f'Liga: {row["league"]} | Pelatih: {row["coach"]} | Key: {row["key_player"]} | Cedera: {row["injury_concern"]}\n')
    print(f'📊 7 PERTANDINGAN TERAKHIR ({row["league"]}):')
    for i in range(1,8):
        m,r,gf,ga=row[f'last7_m{i}'],row[f'last7_r{i}'],int(row[f'last7_gf{i}']),int(row[f'last7_ga{i}'])
        print(f'   {i}. {m:<38} {ri.get(r,"?")}  {gf}-{ga}')
    print(f'   TOTAL: W{row["last7_wins"]} D{row["last7_draws"]} L{row["last7_losses"]} | Form Rating: {fd["weighted_form_rating"]:.1f}/10')
    print(f'\n🎯 PREDIKSI:')
    print(f'   Ranking Model : #{int(md["rank"])} dari 16')
    print(f'   Peluang Model : {md["prob"]:.1f}%')
    print(f'   Peluang MC    : {mc_pct:.1f}%')
    gauge='█'*int(mc_pct*2)+'░'*max(0,40-int(mc_pct*2))
    print(f'   [{gauge}] {mc_pct:.1f}%')
    if mc_pct>=20: v='🔥 FAVORIT KUAT!'
    elif mc_pct>=12: v='💪 KONTENDER SERIUS'
    elif mc_pct>=6: v='⚡ DARK HORSE'
    else: v='🙏 UNDERDOG'
    print(f'   Status: {v}')

"""## 💾 Export & Download"""

export=df.merge(df_m[['team','prob','rank']],on='team').merge(mc_df[['team','pct','count']].rename(columns={'pct':'mc_pct','count':'mc_wins'}),on='team',how='left')
export=export.sort_values('rank')
export.to_csv('ucl_2026_results_v2.csv',index=False)
print('✅ ucl_2026_results_v2.csv tersimpan!')
print(export[['rank','team','league','last7_wins','last7_draws','last7_losses','weighted_form_rating','prob','mc_pct','injury_concern']].to_string(index=False))
try:
    from google.colab import files
    files.download('ucl_2026_results_v2.csv')
    files.download('ucl_form_heatmap.png')
    files.download('ucl_dashboard_v2.png')
    print('\n📥 Semua file didownload!')
except: print('\n💡 Jalankan di Colab untuk auto-download')